spring:
  datasource:
    #   数据源基本配置
    username: root
    password: prinfo
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,lockback
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis-plus:
  #config-location: classpath:mybatis/mybatis-config.xml #指定全局配置文件的位置
  mapper-locations: classpath:mybatis/mybatis/*.xml  #指定sql映射文件的位置
 # type-aliases-package: com.damoncai.springbootmybatisplus.entity  #设置包别名
  global-config:
    db-config:
      id-type: auto #设置全局主键生成策略
      table-prefix: tbl_ #设置统一表开头
      table-underline: true #驼峰命名规则 2.3版本以后默认为true
server:
  port: 9988
